name: Golang 1.20 CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19", "1.20", "1.21"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Print Go version
        run: go version
      - name: Install dep
        run: go mod tidy
      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - name: Vet
        run: go vet -v ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
